name: Release
on:
  push:
    branches:
      - main
      - npm-package
env:
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write   
  contents: read    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267230957:role/github-oidc-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Authenticate with AWS CodeArtifact
        run: |
          echo "Authenticating with AWS CodeArtifact..."
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain rn-generator --domain-owner 533267230957 --region ap-south-1 --query authorizationToken --output text)
          echo "//rn-generator-533267230957.d.codeartifact.ap-south-1.amazonaws.com/npm/rn-generator/:_authToken=${CODEARTIFACT_AUTH_TOKEN}" >> ~/.npmrc
          echo "registry=https://rn-generator-533267230957.d.codeartifact.ap-south-1.amazonaws.com/npm/rn-generator/" >> ~/.npmrc
          echo "//rn-generator-533267230957.d.codeartifact.ap-south-1.amazonaws.com/npm/rn-generator/:always-auth=true" >> ~/.npmrc

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
